kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "mariadb-galera-cluster.fullname" . }}-config-files
  labels:
    app: {{ template "mariadb-galera-cluster.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  empty.cnf: ""
{{- if .Values.configFiles }}
{{ toYaml .Values.configFiles | indent 2 }}
{{ end -}}
