apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mariadb-galera-cluster.fullname" . }}
  labels:
    app: {{ template "mariadb-galera-cluster.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
  {{ if .Values.mysqlRootPassword }}
  mysql-root-password:  {{ .Values.mysqlRootPassword | b64enc | quote }}
  {{ else }}
  mysql-root-password: {{ randAlphaNum 16 | b64enc | quote }}
  {{ end }}
  {{ if .Values.mysqlPassword }}
  mysql-password:  {{ .Values.mysqlPassword | b64enc | quote }}
  {{ else }}
  mysql-password: {{ randAlphaNum 16 | b64enc | quote }}
  {{ end }}
  {{ if .Values.mariabackupPassword }}
  mariabackup-password:  {{ .Values.mariabackupPassword | b64enc | quote }}
  {{ else }}
  mariabackup-password: {{ randAlphaNum 16 | b64enc | quote }}
  {{ end }}
