{{- if .Values.persistence.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app: {{ template "mariadb-galera-cluster.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "mariadb-galera-cluster.fullname" . }}-data
spec:
  storageClassName: {{ .Values.persistence.storageClass | default "" }}
  accessModes:
    - {{ .Values.persistence.accessMode | default "ReadWriteMany" | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{end}}


